version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: remitx
      POSTGRES_PASSWORD: remitx
      POSTGRES_DB: remitx
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build: ./apps/api
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://remitx:remitx@postgres:5432/remitx
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change_me_in_production
      ENCRYPTION_KEY: 0000000000000000000000000000000000000000000000000000000000000000
      STELLAR_NETWORK: testnet
      STELLAR_HORIZON_URL: https://horizon-testnet.stellar.org
      ANCHOR_USDC_URL: https://testanchor.stellar.org
      ANCHOR_NGN_URL: https://testanchor.stellar.org
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./apps/frontend
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - api

  rust-worker:
    build: ./services/rust-worker
    environment:
      REDIS_URL: redis://redis:6379
      STELLAR_HORIZON_URL: https://horizon-testnet.stellar.org
    depends_on:
      - redis

  fraud-service:
    build: ./services/python-analytics
    ports:
      - '8000:8000'

volumes:
  pgdata:
